### PR TITLE
khan camp additions

### PR DESCRIPTION
**Pull request by YuiY1997**
## About The Pull Request

Adds Papa's Palace combination bar and crackhouse 
expands khan camp's second floor 
adds chopping block to khan kitchen and some consistent ingredients.

## Why It's Good For The Game

Since the khans are no longer tied to heaven's night, I think they should have a bar they can use to conduct business.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
Adds khan bar,
redoes khan entrance walkway
adds food processor to khan kitchen, alters fridge contents to be less random and more useful for making food
adds tents and shacks to the second level of the khan base

:cl:
add: Added new things
tweak: tweaked a few things

/:cl:

### CODE REVIEW

**Comment by YuiY1997** [comment]
hold on fixing the problem with the integration tests

**Comment by YuiY1997** [comment]
image
no idea what this is

**Comment by Stutternov** [comment]
Can you provide a screenshot of the changes?

**Comment by YuiY1997** [comment]
image
image
image

here it is in the map maker. It works absolutely fine. This is a port of the work I did for the khan camp in WAD

**Review by Stutternov — APPROVED** [review]

**Pull request merged**
